name: Python CI

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install uv   # like uv init .
        uses: astral-sh/setup-uv@v7

      - name: Install dependencies # like uv sync
        run: uv sync

      - name: Run tests # not installing like pip install pytest instead direct running because we have uv sync
        run: uv run pytest